### ISSUE TITLE
docker-compose build

### ISSUE THREAD

**Issue by leke2015** [ninghao/nest#1]
ERROR: Service 'php' failed to build: Tag 7.0-fpm not found in repository docker.io/library/php

**Comment by ninghao** [comment]
是网络问题吗？昨天我也遇到类似的问题，不能 pull 下镜像。

**Comment by ninghao** [comment]
是网络问题吗？昨天我也遇到类似的问题，不能 pull 下镜像。

**Comment by leke2015** [comment]
是网络问题，这会下载呢。
